# Використовуємо офіційний образ MySQL
FROM mysql:8.0

# Задаємо змінні середовища
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=climate_db
ENV MYSQL_USER=climate_user
ENV MYSQL_PASSWORD=climate_pass

# Порт для MySQL
EXPOSE 3306
